content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields:
    - name: headline
      label: Headline
      type: text
      required: true
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields:
      # ... fields defined here ...